version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile-jdk-dev
    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - '8080:8080'
      - '35729:35729'
      - '5005:5005'

  frontend: # The name of the service
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ./node_modules/.bin/ng serve --host 0.0.0.0 --port 4200"
