version: '3.8'

services:
  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
      target: ${TARGET:-development}
      args:
        - JDK_IMAGE=11.0.19_7-jdk-jammy
        - JRE_VERSION=11-jre-jammy
        - APP_NAME=springboot-angular-docker-boilerplate
    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2
    ports:
      - ${BACKEND_PORT:-8080}:8080
      - '35729:35729'
      - '5005:5005'

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      args:
        - NODE_VERSION=16.20.1-slim
        - NG_VERSION=15
    volumes:
      - ./frontend:/app
    ports:
      - ${BACKEND_PORT:-4200}:4200
