version: '3.8'

services:
  backend:
    container_name: backend

    build:
      context: ./docker/
      dockerfile: Dockerfile-jdk

    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2

    working_dir: /app

    command: sh run.sh

    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
